bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME:$CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
    populate_script: bundle update


test_task:
  env:
    matrix:
      - CIRRUS_CONTAINER: ruby:2.3
      - CIRRUS_CONTAINER: ruby:2.4
      - CIRRUS_CONTAINER: ruby:2.5
      - CIRRUS_CONTAINER: ruby:2.6
      - CIRRUS_CONTAINER: ruby:rc
      - CIRRUS_CONTAINER: jruby:latest
        # --dev improves JRuby startup time
        # --debug reports proper coverage to SimpleCov
        # See https://github.com/jruby/jruby/wiki/Improving-startup-time
        JRUBY_OPTS: --dev --debug

    ## TODO: Add Coveralls (encrypted) key

  container:
    image: $CIRRUS_CONTAINER

  allow_failures:
    $CIRRUS_CONTAINER == 'ruby:rc' ||
    $CIRRUS_CONTAINER == 'jruby:latest'
  skip_notifications:
    $CIRRUS_CONTAINER == 'ruby:rc' ||
    $CIRRUS_CONTAINER == 'jruby:latest'

  <<: *bundle_cache

  test_script: bundle exec rake spec

rubocop_task:
  container:
    image: ruby:2.6
  <<: *bundle_cache
  rubocop_script: bundle exec rake rubocop
